import Link from "next/link";
import { MarketingShell, TrialCta } from "@/components/MarketingShell";
import { pageMetadata } from "@/lib/site";
export const metadata=pageMetadata("はじめ方・設置ガイド｜受付Botの使い方", "登録から質問編集、公開URLの共有、ホームページへの埋め込み、届いた回答の確認まで。初めての方向けに受付Botの使い方と30日無料体験後の条件を説明します。", "/guide");
const steps=[
 ["create","1. 目的と業種を選んで作成","無料登録後に「新しいBotを作る」を選びます。相談受付や問い合わせなどの目的と業種を選び、Bot名・会社名（屋号）・通知先メールを入力します。会社名は回答者に表示されます。サービス説明などの任意項目は後からでも編集できます。"],
 ["questions","2. 聞きたい質問に整える","「質問を編集」でテンプレートの内容を確認します。質問は増やしすぎず、最初の返信に必要なものを優先してください。後で確認できる項目は任意にすると入力負担を減らせます。編集したら保存してください。会社名や通知先は「基本情報」で直せます。"],
 ["preview","3. 動作確認してから公開","「動作確認」で実際に回答してみます。この画面の回答は送信・保存されません。最終確認まで進み、質問の順番や表現が分かりやすいかを確認します。問題なければ「公開・設置」から公開してください。"],
] as const;
export default function GuidePage(){return <MarketingShell><div className="section-wrap"><div className="section-heading"><p className="eyebrow">初めての方向けガイド</p><h1>受付を始めるまでを、順番に。</h1><p>ホームページがなくても大丈夫です。まずは公開URLを共有する方法から始められます。</p></div><div className="grid items-start gap-10 lg:grid-cols-[220px_1fr]"><nav aria-label="ガイド目次" className="rounded-xl border border-slate-200 p-5 lg:sticky lg:top-6"><p className="mb-3 text-sm font-bold">このページの内容</p><div className="flex flex-col gap-3 text-sm text-brand-700">{[...steps.map(([id,title])=>[id,title]),["install","4. URL共有・サイトへの設置"],["responses","5. 届いた回答を確認"],["trial","30日無料体験が終わるとき"],["help","うまくいかないとき"]].map(([id,t])=><a className="py-1 underline-offset-4 hover:underline" key={id} href={`#${id}`}>{t}</a>)}</div></nav><div className="min-w-0 space-y-12">{steps.map(([id,t,b])=><section key={id} id={id} className="scroll-mt-8"><h2 className="text-2xl font-bold">{t}</h2><p className="mt-4 leading-8 text-slate-600">{b}</p></section>)}
 <section id="install" className="scroll-mt-8"><h2 className="text-2xl font-bold">4. URLを共有する、またはサイトに設置する</h2><div className="mt-5 rounded-xl bg-brand-50 p-5"><h3 className="font-bold text-brand-900">一番かんたん：公開URLを共有する</h3><p className="mt-3 text-sm leading-8 text-slate-700">「公開・設置」の公開URLをコピーして、メール署名・SNSプロフィール・ホームページのボタンに貼り付けます。相手は受付Botへの登録なしで回答できます。URLは無料プランでも利用できます。</p></div><details className="mt-4 rounded-xl border border-slate-200 p-5"><summary className="cursor-pointer font-semibold">ホームページ内に表示したい：埋め込み方法</summary><div className="mt-3 space-y-3 text-sm leading-8 text-slate-600"><p>ライト無料体験中、または有料プランでは「埋め込みコード」をコピーできます。これはフォームをサイト内に表示するためのHTMLです。</p><p>サイトを自分で編集する場合は、HTMLを入力できるブロックや欄に貼り付け、更新して表示を確認してください。WordPressでは通常「カスタムHTML」ブロックを使います。ただし利用しているプラン・権限・サイト設定でHTMLが制限される場合があります。</p><p>制作会社に任せている場合は、埋め込みコードと「どのページのどの位置に表示したいか」を渡します。コードが使えないサイトでは、公開URLへリンクするボタンを設置してください。</p><p className="font-medium text-slate-900">体験終了後に無料プランへ戻ると、埋め込み表示は停止します。受付を続ける場合は公開URLを案内するか、有料プランをお申し込みください。</p></div></details></section>
 <section id="responses" className="scroll-mt-8"><h2 className="text-2xl font-bold">5. 届いた回答を確認し、連絡する</h2><p className="mt-4 leading-8 text-slate-600">回答は「届いた回答」に保存され、内容と連絡先を確認できます。「新規」「対応中」「完了」を使い分けて対応状況を整理します。返信は普段お使いのメールや電話で行ってください。</p><p className="mt-4 leading-8 text-slate-600">通知メールが見当たらない場合も、まず管理画面の回答一覧をご確認ください。通知先の入力間違い・迷惑メールフォルダー・受信設定を確認します。</p><div className="mt-4 rounded-xl border border-slate-200 p-5 text-sm leading-7"><strong>実際の公開URLで試す場合</strong><p className="mt-2 text-slate-600">動作確認画面とは異なり、公開URLから送信したテスト回答も保存され、通知や回答件数の対象になります。氏名を「動作テスト」などにすると区別できます。</p></div></section>
 <section id="trial" className="scroll-mt-8"><h2 className="text-2xl font-bold">30日無料体験が終わるとき</h2><p className="mt-4 leading-8 text-slate-600">新規登録から30日間は、Bot1個・回答数無制限・ホームページへの埋め込みを利用できます。無料体験だけならカード登録も解約手続きも必要ありません。正確な終了日時は「プラン・請求」で確認できます。</p><dl className="mt-5 divide-y divide-slate-200 rounded-xl border border-slate-200 px-5 text-sm">{[["有料契約をしない場合","自動で無料プランへ戻ります。自動課金はありません。Bot・保存した回答は体験終了だけでは削除しません。"],["公開URL","無料プランでも利用できます。月30回答の上限が適用されます。"],["ホームページへの埋め込み","無料プランでは表示できません。公開URLへのリンクに切り替えるか、有料プランをお申し込みください。"],["月30回答の数え方","日本時間の暦月で数えます。無料体験中に受け付けたその月の回答も含みます。既に30件以上なら、その月の新しい受付は停止し、翌月に再開します。"],["ライトを継続したい場合","無料体験終了後に料金ページから月980円のライトプランを選び、ご自身で決済手続きを完了してください。契約後は月ごとに更新されます。"]].map(([label,value])=><div className="py-4" key={label}><dt className="font-semibold">{label}</dt><dd className="mt-2 leading-7 text-slate-600">{value}</dd></div>)}</dl><Link href="/pricing" className="mt-4 inline-block text-sm font-semibold text-brand-700 underline">全プランの料金・条件を確認する →</Link></section>
 <section id="help" className="scroll-mt-8"><h2 className="text-2xl font-bold">うまくいかないとき</h2><div className="mt-5 divide-y divide-slate-200">{[["公開できない","基本情報に会社名（屋号）が入っているか、質問が1つ以上あるか確認してください。下書きのままでは公開URLから回答できません。"],["新しいBotを作れない","無料・ライトはBot1個までです。作成済みの下書きを編集できます。複数の窓口を分けたい場合は3個のスタンダード、10個のプロを選べます。"],["保存や送信でエラーになる","画面を閉じる前に接続を確認し、表示された内容に従って再試行してください。入力を直す必要がある場合は該当箇所を修正します。入力中の内容はブラウザを閉じると失われる場合があります。"],["受付Botに向かない用途","AIによる自由回答、予約枠と連動した自動確定、ファイル添付、フォームでの料金決済、多言語自動翻訳は提供していません。"]].map(([q,a])=><details className="py-4" key={q}><summary className="cursor-pointer font-semibold">{q}</summary><p className="mt-3 text-sm leading-8 text-slate-600">{a}</p></details>)}</div><p className="mt-6 text-sm leading-7 text-slate-600">解決しない場合は <a href="mailto:support@chatbot-support.com" className="break-all text-brand-700 underline">support@chatbot-support.com</a> へ。ページの場所と起きたことをお知らせください。パスワードや回答者の個人情報は送らないでください。</p></section>
 </div></div></div><TrialCta title="流れがわかったら、最初の受付を。"/></MarketingShell>;}
